DROP TABLE IF EXISTS issue_comments CASCADE;
DROP TABLE IF EXISTS issue_labels CASCADE;
DROP TABLE IF EXISTS issue_assignees CASCADE;
DROP TABLE IF EXISTS issues CASCADE;
DROP TABLE IF EXISTS milestones CASCADE;
DROP TABLE IF EXISTS labels CASCADE;
